# Generated by Django 4.2.3 on 2024-04-14 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='googleID',
            new_name='googleId',
        ),
    ]
