# Generated by Django 4.2.3 on 2026-01-20 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('notification_type', models.CharField(choices=[('POST_LIKE', '게시글 좋아요'), ('DISASTER_ALERT', '재난 알림'), ('SYSTEM', '시스템 알림')], default='SYSTEM', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'NotificationMessage',
                'verbose_name_plural': 'NotificationMessages',
                'db_table': 'notification_message',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'NotificationSetting',
                'verbose_name_plural': 'NotificationSettings',
                'db_table': 'notification_setting',
            },
        ),
    ]
